export default [
    { id: 1, image: 'https://images7.alphacoders.com/964/thumb-1920-964116.jpg', name: 'Avengers Infinity War', price: '$29.99', siteLink: 'https://example.com/product1', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson, the Falcon and Bucky Barnes turned White Wolf", link: "https://www.youtube.com/watch?v=6ZfuNTqbHE8", height:200 },
    { id: 2, image: 'https://wallpapers.com/images/featured/iron-man-ouqxo5w2b59h0042.jpg', name: 'Iron Man 3', price: '$49.99', siteLink: 'https://example.com/product2', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson", link: "https://www.youtube.com/watch?v=Ke1Y3P9D0Bc", height:220},
    { id: 3, image: 'https://images4.alphacoders.com/621/thumb-1920-621465.jpeg', name: 'Spider Man X', price: '$19.99', siteLink: 'https://example.com/product3', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson, the Falcon and Bucky Barnes turned White Wolf", link: "https://www.youtube.com/watch?v=JfVOs4VSpmA", height:250 },
    { id: 4, image: 'https://images3.alphacoders.com/103/thumb-1920-1033559.jpg', name: 'Black Panther 2', price: '$99.99', siteLink: 'https://example.com/product4', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson, the Falcon and Bucky Barnes turned White Wolf", link: "https://www.youtube.com/watch?v=xjDjIWPwcPU", height:300 },
    { id: 5, image: 'https://images4.alphacoders.com/135/thumb-1920-1352019.png', name: 'Captain America 4', price: '$39.99', siteLink: 'https://example.com/product5', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson, the Falcon and Bucky Barnes turned White Wolf", link: "https://www.youtube.com/watch?v=7SlILk2WMTI", height:200 },
    { id: 6, image: 'https://wallpapers.com/images/featured/hawkeye-a326pji23dkf26xm.jpg', name: 'Hawkeye', price: '$59.99', siteLink: 'https://example.com/product6', info: "Marvel spin off introduces the backstories of Captain America's two friends Sam Wilson, the Falcon and Bucky Barnes turned White Wolf", link: "https://www.youtube.com/watch?v=5VYb3B1ETlk", height:220 },
    { id: 7, image: 'https://images7.alphacoders.com/964/thumb-1920-964116.jpg', name: 'Avengers Endgame', price: '$34.99', siteLink: 'https://example.com/product7', info: "The epic conclusion to Marvel's Infinity Saga", link: "https://www.youtube.com/watch?v=TcMBFSGVi1c", height:180 },
    { id: 8, image: 'https://wallpapers.com/images/featured/iron-man-ouqxo5w2b59h0042.jpg', name: 'Iron Man 2', price: '$29.99', siteLink: 'https://example.com/product8', info: "Tony Stark faces a new enemy while confronting his legacy", link: "https://www.youtube.com/watch?v=BoohRoVA9WQ" , height:220},
    { id: 9, image: 'https://c4.wallpaperflare.com/wallpaper/997/794/382/miles-morales-spiderman-miles-morales-spider-man-peter-parker-spider-gwen-hd-wallpaper-preview.jpg', name: 'Spider Man: Homecoming', price: '$19.99', siteLink: 'https://example.com/product9', info: "Peter Parker returns home to prove himself as a hero", link: "https://www.youtube.com/watch?v=U0D3AOldjMU",height:250 },
    { id: 10, image: 'https://images3.alphacoders.com/103/thumb-1920-1033559.jpg', name: 'Black Panther', price: '$89.99', siteLink: 'https://example.com/product10', info: "T'Challa returns home to rule Wakanda and face a powerful adversary", link: "https://www.youtube.com/watch?v=xjDjIWPwcPU" ,  height:320},
    { id: 11, image: 'https://images4.alphacoders.com/135/thumb-1920-1352019.png', name: 'Captain America: The Winter Soldier', price: '$44.99', siteLink: 'https://example.com/product11', info: "Captain America battles the mysterious Winter Soldier", link: "https://www.youtube.com/watch?v=7SlILk2WMTI", height:240 },
    { id: 12, image: 'https://wallpapers.com/images/featured/hawkeye-a326pji23dkf26xm.jpg', name: 'Avengers: Age of Ultron', price: '$64.99', siteLink: 'https://example.com/product12', info: "The Avengers unite to defeat the rogue AI Ultron", link: "https://www.youtube.com/watch?v=tmeOjFno6Do" , height:150},
    { id: 13, image: 'https://c4.wallpaperflare.com/wallpaper/296/400/37/movie-avengers-infinity-war-black-panther-movie-black-widow-wallpaper-preview.jpg', name: 'Thor: Ragnarok', price: '$32.99', siteLink: 'https://example.com/product13', info: "Thor faces off against Hela in a fight for Asgard's future", link: "https://www.youtube.com/watch?v=ue80QwXMRHg", height:200 },
    { id: 14, image: 'https://wallpapers.com/images/featured/iron-man-ouqxo5w2b59h0042.jpg', name: 'Guardians of the Galaxy', price: '$39.99', siteLink: 'https://example.com/product14', info: "A group of intergalactic criminals teams up to save the universe", link: "https://www.youtube.com/watch?v=d96cjJhvlMA", height:390 },
    { id: 15, image: 'https://images6.alphacoders.com/134/thumb-1920-1341933.jpeg', name: 'Captain Marvel', price: '$29.99', siteLink: 'https://example.com/product15', info: "A space hero marvel  learns the mystic arts to defend reality", link: "https://www.youtube.com/watch?v=HSzx-zryEgM" , height:270}
];
